apiVersion: v1
kind: Secret
metadata:
  name: device-management-secrets
  namespace: bootstrap
stringData:
  PUBLIC_BASE_URL: "https://<DGX_HOSTNAME>/bootstrap"
  DM_ENROLL_URL: "/bootstrap/enroll"
  KEYCLOAK_ISSUER_URL: "https://<DGX_HOSTNAME>/relay-assistant/keycloak"
