{{- if .Values.matomo.networkPolicy.create }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "helper.fullname" . }}
  labels: {{- (include "helper.labels" (dict "root" . "componentName" "matomo")) | nindent 4 }}
spec:
  policyTypes: {{- toYaml .Values.matomo.networkPolicy.policyTypes | nindent 2 }}
  {{- with .Values.matomo.networkPolicy.ingress }}
  ingress: {{- toYaml . | nindent 2 }}
  {{- end }}
  {{- with .Values.matomo.networkPolicy.egress }}
  egress: {{- toYaml . | nindent 2 }}
  {{- end }}
{{- end }}
