{{- if .Values.secret.enabled -}}
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: {{ .Values.secret.destination.name }}
spec:
  mount: {{ .Values.secret.mount }}
  path: {{ .Values.secret.vaultPath }}
  type: kv-v2
  vaultAuthRef: vault-auth
  destination:
    create: true
    name: {{ .Values.secret.destination.name }}
    type: {{ .Values.secret.destination.type }}
    transformation:
      templates:
        DB_PASS:
          text: "{{`{{- get .Secrets \"mariadb-password\" -}}`}}"
{{- end -}}