apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "device-management.name" . }}-data
  labels:
    {{- include "device-management.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.app.persistence.dataSize | default "1Gi" }}
---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "device-management.name" . }}-content
  labels:
    {{- include "device-management.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.app.persistence.contentSize | default "1Gi" }}