apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: bootstrap-extras
  namespace: bootstrap
  annotations:
    nginx.ingress.kubernetes.io/use-regex: "true"
    nginx.ingress.kubernetes.io/rewrite-target: /$2
    nginx.ingress.kubernetes.io/proxy-body-size: "100m"
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - <SCALEWAY_HOSTNAME>
      secretName: bootstrap-tls
  rules:
    - host: <SCALEWAY_HOSTNAME>
      http:
        paths:
          - path: /relay-assistant(/|$)(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: relay-assistant
                port:
                  number: 80
