apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: bootstrap-root
  namespace: bootstrap
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: "100m"
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - bootstrap.fake-domain.name
      secretName: bootstrap-tls
  rules:
    - host: bootstrap.fake-domain.name
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: device-management
                port:
                  number: 80
