{{- if .Values.filebrowser.enabled -}}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "device-management.name" . }}-filebrowser-db
  labels:
    {{- include "device-management.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.filebrowser.persistence.size | default "1Gi" }}
{{- end }}