{{- if .Values.filebrowser.enabled -}}
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: filebrowser-config
  labels:
    {{- include "device-management.labels" . | nindent 4 }}
spec:
  vaultAuthRef: {{ .Values.vault.vaultAuthRef | quote }}
  mount: {{ .Values.vault.mount | quote }}
  type: {{ .Values.vault.type | quote }}
  path: {{ .Values.vault.pathFilebrowser | quote }}
  refreshAfter: {{ .Values.vault.refreshAfter | quote }}
  destination:
    create: true
    name: "{{ include "device-management.name" . }}-filebrowser-config"
    type: kubernetes.io/basic-auth
{{- end }}
