{{- if .Values.ingress.enabled -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: device-management-route
  labels:
    {{- include "device-management.labels" . | nindent 4 }}
  {{- with .Values.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- if .Values.ingress.className }}
  ingressClassName: {{ .Values.ingress.className }}
  {{- end }}
  {{- if .Values.ingress.tls }}
  tls:
    {{- range .Values.ingress.tls }}
    - hosts:
        {{- range .hosts }}
        - {{ . | quote }}
        {{- end }}
      secretName: {{ .secretName }}
    {{- end }}
  {{- end }}
  rules:
    {{- $hostnames := .Values.ingress.hostnames | default (list .Values.ingress.host) }}
    {{- range $hostnames }}
    - host: {{ . }}
      http:
        paths:
          - path: {{ $.Values.app.path | default "/" }}
            pathType: Prefix
            backend:
              service:
                name: device-management
                port:
                  number: {{ $.Values.app.service.port }}
          {{- if $.Values.adminer.enabled }}
          - path: {{ $.Values.adminer.path | default "/adminer" }}
            pathType: Prefix
            backend:
              service:
                name: adminer
                port:
                  number: {{ $.Values.adminer.service.port }}
          {{- end }}
          {{- if $.Values.filebrowser.enabled }}
          - path: {{ $.Values.filebrowser.path | default "/files" }}
            pathType: Prefix
            backend:
              service:
                name: filebrowser
                port:
                  number: {{ $.Values.filebrowser.service.port }}
          {{- end }}
    {{- end }}
{{- end }}
