{{- if .Values.vault.enabled }}
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: device-management-psql-user
  labels:
    {{- include "device-management.labels" . | nindent 4 }}
spec:
  vaultAuthRef: {{ .Values.vault.vaultAuthRef | quote }}
  mount: {{ .Values.vault.mount | quote }}
  type: {{ .Values.vault.type | quote }}
  path: {{ .Values.vault.pathApp | quote }}
  refreshAfter: {{ .Values.vault.refreshAfter | quote }}
  destination:
    create: true
    name: {{ .Values.cnpg.credentials.existingSecrets.app.secretName | quote }}
    type: kubernetes.io/basic-auth
---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: device-management-psql-admin
  labels:
    {{- include "device-management.labels" . | nindent 4 }}
spec:
  vaultAuthRef: {{ .Values.vault.vaultAuthRef | quote }}
  mount: {{ .Values.vault.mount | quote }}
  type: {{ .Values.vault.type | quote }}
  path: {{ .Values.vault.pathAdmin | quote }}
  refreshAfter: {{ .Values.vault.refreshAfter | quote }}
  destination:
    create: true
    name: {{ .Values.cnpg.credentials.existingSecrets.postgres.secretName | quote }}
    type: kubernetes.io/basic-auth
---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: device-management-config
  labels:
    {{- include "device-management.labels" . | nindent 4 }}
spec:
  vaultAuthRef: {{ .Values.vault.vaultAuthRef | quote }}
  mount: {{ .Values.vault.mount | quote }}
  type: {{ .Values.vault.type | quote }}
  path: {{ .Values.vault.pathConfig | quote }}
  refreshAfter: {{ .Values.vault.refreshAfter | quote }}
  destination:
    create: true
    name: "{{ include "device-management.name" . }}-config"
    type: kubernetes.io/basic-auth
{{- end }}
