apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: device-management
  namespace: bootstrap
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: device-management
  minReplicas: 4
  maxReplicas: 20
  behavior:
    scaleUp:
      stabilizationWindowSeconds: 0
      policies:
        - type: Percent
          value: 100
          periodSeconds: 30
        - type: Pods
          value: 6
          periodSeconds: 30
    scaleDown:
      stabilizationWindowSeconds: 300
      policies:
        - type: Percent
          value: 20
          periodSeconds: 60
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 55
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: 70
