apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: bootstrap-root
  namespace: bootstrap
spec:
  rules:
    - host: bootstrap.home
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: device-management
                port:
                  number: 80
