apiVersion: v1
kind: Secret
metadata:
  name: device-management-secrets
  namespace: bootstrap
stringData:
  PUBLIC_BASE_URL: "http://bootstrap.home"
  DM_ENROLL_URL: "/enroll"
  KEYCLOAK_ISSUER_URL: "http://bootstrap.home/relay-assistant/keycloak"
